### ISSUE TITLE
TypeSafeEnum with JsonSerializer.Deserialize

### ISSUE THREAD

**Issue by spaul-ow** [simonmau/enum_ext#1]
I can see SystemTextJson.Tests that deserialize TypeSafeNameEnum. 
We are having problems deserializing TypeSafeEnum throwing System.Text.Json.JsonException where we have additional properties within our enumeration sealed class very similar to your example TypeSafeEnum<YearlyPrice, int>, do you have examples / Tests that deserialize TypeSafeEnum?

**Comment by mjuen** [comment]
`TypeSafeNameEnum` is actually just a `TypeSafeEnum` with a `Name` property.

https://github.com/simonmau/enum_ext/blob/c9bb513ac3aa0b6c34f5f474ef40ba2349b6027b/Enum.Ext/Enum.Ext/TypeSafeNameEnum.cs#L5-L15

However, I still tried the deserialization of a `YearlyPrice` item

```csharp

public void Test_ConvertYearlyPriceFromJsonWithSerializerOptions()
{
	var serializerOptions = new JsonSerializerOptions
	{
		Converters = { new JsonTypeSafeEnumConverterFactory() }
	};

	var tempClass = JsonSerializer
		.Deserialize<ClassToSerialize<YearlyPrice>>("{\"Item\":1}", serializerOptions);

	tempClass.Item.Should().Be(YearlyPrice.Price_2018);
}

```

which worked just fine.

**Comment by spaul-ow** [comment]
Thanks for the prompt reply! 

It turns out that we are forced to use Newtonsoft by a 3rd party and what we are finding is that with Newtonsoft the serialized object is being returned as "{"YearlyPrice":{"Price":15.99,"ValidFrom":"2018-01-01T00:00:00","ValidTo":"2018-12-31T00:00:00","Id":1}}" rather than "**{"YearlyPrice":1}**" that the Deserializer is expecting. 

If we use SystemTextJson it serializes to "{"YearlyPrice":1}" and works. 

We have installed the Enum.Ext.NewtonsoftJson library and have NewtonSoft.Json 12.0.2.

Are we missing something else?

**Comment by mjuen** [comment]
> It turns out that we are forced to use Newtonsoft by a 3rd party and what we are finding is that with Newtonsoft the serialized object is being returned as "{"YearlyPrice":{"Price":15.99,"ValidFrom":"2018-01-01T00:00:00","ValidTo":"2018-12-31T00:00:00","Id":1}}" rather than "**{"YearlyPrice":1}**" that the Deserializer is expecting.

That should not happen. Can you make sure, that the class is either annotated with
```csharp
[JsonConverter(typeof(JsonTypeSafeEnumConverter))] 
````
or you make use of `JsonTypeSafeEnumConverter` for a global configuration?

**Comment by spaul-ow** [comment]
We had used the annotations, using different ones for Newtonsoft and SystemTextJson.

I've managed to create a test mimicking what we are trying to do that also throws an exception within Enum.Ext.NewtonsoftJson.Tests. Please try the folowing:

```csharp
[Test]
public void Test_YearlyPrice_ConvertToJsonWithSerializerOptions()
{
	var tempClass = new ClassYearlyPriceToSerialize
	{
		YearlyPrice = YearlyPrice.Price_2018
	};

	var serializerOptions = new JsonSerializerSettings
	{
		Converters = { new JsonTypeSafeEnumConverter() }
	};

	var json = JsonConvert.SerializeObject(tempClass, serializerOptions);

	json.Should().Be("{\"YearlyPrice\":1}");

	var deSer = JsonConvert.DeserializeObject<ClassYearlyPriceToSerialize>(json);

	deSer.YearlyPrice.Id.Should().Be(1);
}
		
public class ClassYearlyPriceToSerialize
{
	public YearlyPrice YearlyPrice { get; set; }
}
```

**Comment by mjuen** [comment]
```csharp
var deSer = JsonConvert.DeserializeObject<ClassYearlyPriceToSerialize>(json);
```

Is missing the `serializerOptions` parameter. With 

```csharp
var deSer = JsonConvert
       .DeserializeObject<ClassYearlyPriceToSerialize>(json, serializerOptions);
```

it works.

**Comment by spaul-ow** [comment]
Doh! too many tests getting copied about ... yes that works.

Were obviously missing something else as in our environment the Test fails at:
json.Should().Be("{\"YearlyPrice\":1}");

since the entire YearlyPrice structure is included in the json... will keep looking

**Comment by spaul-ow** [comment]
Unit tests are now working.... at the top of the enumerated class I had to change:
[JsonConverter(typeof(JsonTypeSafeEnumConverter))]
To
[Newtonsoft.Json.JsonConverter(typeof(JsonTypeSafeEnumConverter))]
and then the object serialized correctly.
Must be picking up a different JsonConverter without the explicit reference.
Thanks for your help
